# Generated by Django 2.2.13 on 2020-06-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='brithday',
            new_name='birthday',
        ),
    ]
